ALTER TABLE public.creators
  ADD COLUMN IF NOT EXISTS deal_type text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS rate text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS platform text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS contract_start date DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS contract_end date DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS wl_status text DEFAULT 'none',
  ADD COLUMN IF NOT EXISTS wl_page_name text DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS wl_page_id text DEFAULT NULL;